import Head from 'next/head'
import Hero from '../components/Hero/Hero'
import Presentation from '../components/Presentation'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <Hero />
            <Presentation />
        </div>
    )
}
