import Head from 'next/head'
import React, { useState } from 'react'
import BetaSection from '../components/Features/BetaSection'
import Compare from '../components/Pricing/Compare'
import Plans from '../components/Pricing/Plans'
import PricingHero from '../components/Pricing/PricingHero'

const Pricing: React.FC = () => {
    const [isYearly, setIsYearly] = useState(false)
    const billingToggler = () => {
        setIsYearly(!isYearly)
    }
    return (
        <div className="w-full mt-[72px]">
            <Head>
                <title>Pricing</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <PricingHero />
            <Plans
                isYearly={isYearly}
                billingToggler={billingToggler}
            />
            <Compare />
            <BetaSection />
        </div>
    )
}

export default Pricing
